name: lab5
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - pygame
  - matplotlib
  - seaborn
  - scipy
  - jupyter
  - ipykernel
  - pip:
    - pytest
    - gymnasium